#!/bin/bash

clear
echo -e "================================================="
echo -e "#  Premium Auto Script By Adjie Poetra Pratama  #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & Debian 10 64 bit               #"
echo -e "# For Ubuntu 18.04 & Ubuntu 20.04 64 bit        #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Build Up By Adjie Poetra Pratama              #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# Adjieptra                                     #"
echo -e "# Allah SWT                                     #"
echo -e "# My Family                                     #"
echo -e "# Admin BLUESSH & VPNSTORES                     #"
echo -e "# Bluessh                                       #"
echo -e "# Horass                                        #"
echo -e "# Pablo Escobar                                 #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
